---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBFRco0h4uSptXvcGZYqoe88s8SeyeFQSlCAngksO+PmpNB/N+RVkoaAUndn8t+/wDbtyN8A7sqevf8CnSd3Dp8DLgQxOoK9w0fWLv6aeNVcmmTUY/ihC659WcxD8LTsPlnjLQMyxN1MuIelg427Jg8/7ue3YbTu68HCsBX0n95gX7yxRh8FixIZnc7VXxw+hlZQUphdjORdHYpI7IUSWkMHQG7zepqFgNkZwRsUAGLw7m/Perp/mliiwFwDaQisHAsneuivn6zF3l73TMKDjyswBlEYNh68NRLFuUNiFma7sxvty59cYx0GeRnir/AzbDO4OdjJfS8+LoU1Ya8uDteFBkftnLbnga0ci3ANjsCpvFiMSfh0H0cLPedSyxsrl5s29jgjai+R7Bk0y6fHTwdbKcLqdlnrFsGa8+o8sUnvLK6zZZwDIubsKhsQD9nmgdZyowRL/B1dJ7tl3pt3s3+0P50qsmY5V4tTrOjoIeezrIhkKsjXds5Hw7hsu4Y5JDFe/7uaNVAO//sLWMBGQ/wuvy+JOlMsKw8OAmGhc9rqDby62y5xUzTjnZ/Um2hJzZdlaohlqRbOPS347t4Uv1J6AXJAmzHsZbKmjVsNZevbbYITYMltm/m3Zg0WalpQNFHYeMe5D6c8vv9vqjaoPFZXmQwz0dQi61xVCPAHl6bGphY5X2ZkgccFJb5dD4Ehho7VjqtsqU1/A==
    admin-user: AgCVvZHCqTBF6AGu1fYi1Sk27aR8MWGfWB00u5/DjaKiPJgyNzcfe3S68eVTbUK9I0huxIvulokCEsMz5YFzB5ejdN12aAGNyTpVx5b11h2CS1Dsxs/vq2dPLvJqJBkg5+b12a/Wy0AX4yzNYfk1VcggidwwZYG6sVrCUNnioz/w5wY6EiE0doQO6R/4/TsS2AWqLbEV7JBRmTWP/FJELiIjhuyo6q02tTus4wEC3w9+mA/sTKzkPpxzeAbVZDRMkWHobpKcpvcguR8vl7jKLzVl0qG1n+qea2tmLHZ7Vrg6mRXXxMLy9B3zm1OzAN1qd6vh4070FX7xzc/qWRlI8SntbaX7JXt9B0KyqSCJ7kuOQbTbvPOFJDzUJubqpCMTE6wFa02PuZvyBJd1OSaUpKNPaJFuvQQXEe2azKlXsmqDG7nDS5mHSFDbNQFvN7BkiAMkRl8PFGqO6LH9F9Fj0XhLdP3YcVJzWHE9TAuyCkFG27g+mD3d1mE0OOy3vLrWpMNoyTCIZbhl1nrcuWD0RkLgC821ISKGn6JXddEFFpGIbw5orQGwPImovkyj5J9Nxz6OogcDbISpvngavZ7RUDcGI2GTj6wiY4HYwQeh64PjyERTyc35WnFgCO8TiSZzpyCxbYr2vOEWijFfdezzAKPK0M5yjWeHjdrvvs+rOR06AYGX4KJWVd5OvEZSCcmIoOX2b45eWg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-admin-secret
      namespace: monitoring
