---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBg32M5qy+AetmG8ARU6I7etRCe29RWROSvAi61kHa4UBdcuTyHC3BmQBkmvor2860pDc7NEGa2zs65enjctYkR0M9AVyp1BDUAV0+uq7zvjbNVK2y7/ZU48EQm7NbkF+3MQOGR9e3RgVuERyQxYhbIanZlU6dLis+p+kpCgfOaynru66PXKoqOwRsYfTmfI0K9Fc80/R2KxRch68AOfzcAKepc6QejojiaD2KyW537vEXrisO/uxKV5kS/8KmX/EEG8eD9w9MrJQ2XeM/5ZLNb3Y+CJ+KiUCSUEohIckrhm8CeVk6pZh9Jr9h2QYf+Of1okqwxyNHfPGvuL90XOb53Y+cRTVWhW9aExaN1ZyY2IsSiXaZjlXloRBX3L9ji5EXMJwKXUZK6L2ykulAA348F/JNHLKjnIUFkzbrNfmyg27Z0k6wQwRtEzDTJp3IFweLBBTwW8hiVB5cfky92RSlU5c6tjpja3X+a49GH28NpDOywGkD56I1gk9fKHTQVD0qTSB78WYlTtSBjNtDQjPxsYiAiA2Qv43MjJF1whN2YdE8Uj+nagiBFfP+x3PblWUdXNtSk68s3eH4QL+JtfqvhVNNdFT9Pe9OKEDuTcXvlWuj2/ZYEFsaaAU2L1p2okV0/v1XhA3nuDFdDOfYJphw8/Wif/hPXYfX+1C2DISAfgoADneCyGmDdRvzBpzV9WUE0RaW306UNFaC2zHGHuH2jHaBVkogpCtoZS2klbU43EkOlj/hIfYUBsJhiJzHVeUNf2H/JfcO6dLfbmgQX81uSxv9ZUwZ2E55uBGve4QQcUHeeLmRD25mBXX797rF0pfKnbiZoIKoklrSoUFcrdpk/us8uFPHpXkxWxIq8mlseO/BNO9nmUrX22wgHL7nCjXah6Apx/M/Ao97nViY1pT/0NGo4BM71pBjoyIPX
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
