---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB4+9Q2AlEI7iCEFmROMpL+apFgvixbJ0KHbI86iXHV8NWZxgw01cYnoiL3/QaUsHe2q3X46x+2tkMocEQwwGzAhhDTLGpGRfzIxB4580Al+CF/zRKMa34FZAKn9g/sM3sfrtyvr8ygvu5Tn5CV3mms/ECIEOpFnaQc6X/99Ua+y2Cnx48JaTCH6aM3JX5dH9X/5FeIzIxCVAH/wL3wVhw+AT0qWGMwxSPFn6sYH4XKdEwuY68QdOtK/h+6AXy3UOTg+w5LqIwDizgKIzPLB0oDLCwYtvpmbOdAKslxwEN3O4cmBIaPQL2PCFJMoNCP2vFnfMXzzkchMvoKQM+RN7xTgt3mE1nMmlQ2saI4pa0BTvG1rOkQUoSdhn7DJYrV4S8oLDg51Bgrc90RGfOGbqjLjQZjqwjsCqlI9FyVZGE3SnA1lOp1XjE35OdsjGb7W8yn9mPpZhbtvhcO4rm0b/DG0s/xTr+BMA2O+AmGlKae4+RkNcJhlI9uirzh3/Os/dzGer+C7b7ZSz1tyW/TmORPi+QOImmIzdlcWX/wJ+s6qETStwC+88pXFWLptZ/sNonfr+kFlG9ZAw7sA0/lR/r/qznvw5TcuO5403ZdVxAEQAzjKiZjK3/RCheOcQIn/MM0Qx9OXidqc1Q53yFZxoCWg199M6PY6wYi9UE/vRSYeQ7pcPJwHJ1YUAPJGInk/VL7VGLGo4OwttfsMpm24ib8R5p6tI8mzICPori9xHwk7fdAog9VVbiqH9FOMPZZK9VPcwHa6RhmdmFcU7vbv5c+juFXQcgbzRn13iBkd6vc+ULJr3zJGpAN/pwg33Jh3QOqVT05WJBuGGSJCvJwTVctdi8H0dP3Jqaw2M84htr6m1P+iI0SbC1glGktQSqquINdwx9MtSv7WcNnG060kUv/p0IIW905363rReRA
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
