---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgDgER56f5QHWwFfRqKZFcpwmqscAX4jM0GozPaHqfJqT2rHusIeP6zToL1AKijORcFabQK0izftPD4yz8LxVIZi1FD+iKauRLkt8H2jABrS03m62S05YcQxGvtO3YAXqpEFKYZWc9VyrSTuDjxDvOLpqbxxamDYRxloM8lMq7keAOON1LYVbVioexpk2UZvo+B8rVopjrnofr+SSXGaq+mle7Pk76XJZLSbddCRwAryHFGZC1adFpHcAZykA9GJhxsqc2rD4fYd2u6cgS54ghcxRDjtFWOXhMw4ofM18GLoedCWcIhjeqWKEdwl4Fj6nRnzqmB8+DR06kNyb0n1H7o8nNG7qUTEB7WhXSCECNrilSR0JyUD7NrYKrvMNm0HIDd3kRzbA2xIvd2op3DJ7bZSpYHABi5DWja9N34RdNTtYeXr2Pe+QPMnmwRZIIxY8yCa+fl4t6E+DFwaYsikMbDBRMDXi/qSXZsLXXexLemBZsZrpyIEm9p3AFd1PLIXmjhLlwLL/p67223twAQhPb0+NsbiBGmHmgDKcx3BvDNKY37jladFNcDFqbylALp6z9+rtSjnU7dJGHKh+NobOssXQ5dEIESVMvnnB1EOe4Eldb/bI2u+ErLJiYk19K6oyZwRfWgqn3HuL4mpz/JWLghWLmOQxKl4LeNZC9k5IfRm2l4drc26oycS6v+ZIOVFo1uIOysjUD2hKneffrpK49h5iQr4fx2urw+SJe7bmP3KyKvrbHiuzMQ4Q/T6ZhJl2QRiijBnG2F59WbKCv7DinWezHs9+nInqOZh5Cgd3Z8cUAFWVy4mMdsrilwlFfvSYWAuMHlwszFwBkit9UnPRSkZcnZffPH1NKn2i86e74c8GiHaIo4IvLDxKnnf7JOaE8SzazOpHY7eAYePhC6hGjpy9LZf7/JxXyU9NPKP
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
