---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBnyNh9GXQGfVcRq6hgw1RxHN7h9n3/BwrgcuHBCl9H/9Po34GzNJAmWJMY4mwSsVxkd5yiQQavjF/hpArCdP85eCDZn0lc61s81oYobtnSEcjK7jW+cSrnlh8OHI32q1hEce9tSW02d1tbQbUwu8fMz+yrsEvFFKhI+aRPyV2jisD4OqA803Jaqvi06HT4NSXeD/PJGcm+CXYDEBfANJTPSRwitZRBbfKooXiWsX3mO3lVOiNez84GiTI2lkieynhb9Ayig064m+9fD6n6l5wgJlvzzwe5VwZngb5Qi4nP/41Or81AHAcfdJ2zvqwByePBV3cxmf2QySPREO5uFeoM3gcIAj2H5OkgBaCTIxhVdlsx4/GL0nPu3LWy362596r9Lci9roDCywk23PM5g7onBPV7qZloD+Uz/qvaPd3E6nWgbZFNaMqVrNcxWCrQHElmx/rwqvZpp04RTctpZzHLrJczxMVqmGIIfL2dEgkxGQtQcnhyvlA0zn8SotOHkdk0pMFckqCJQT+/a9zeUfK6qEibwq93I8f/jhC4olFL0bG8Hu5SgPM6wqWzy1gcL8Fz6/BG7CqiQfw/N82OpC1OLDmSS7nRivCu4flZ01zsfPqVDVvHtRVPWSjfTec/tj7yNGF66XeAi9T5ioGxMfwIgkJmQCQgHCd05plkerOp3UcPUztO/DByOo+DbsWBhhXFeSQov+/SfO0Viep5955tq3gEDX99H8OH8a59/8XTjlYvjBETX25ruBWeCgXW1fCTbpBNAkvlcOqAYsXhuTCoL/xbDHroVilZwrhB92nJ4TgfqejBdy73TQU5gSWqCB1OkJ70aANx8R9cp3UlY9mHD8uUuFQSWewAUK5/vyepiz9dvQjdyD+HK+f4+mehvIOmpnzn0Cr+7PKeNLi1AObzimWmVTPQco6syYZp
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
