api:
  replicaCount: 1
  image:
    repository: ghcr.io/richonn/kubeforge-api
    tag: sha-2812875
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 50

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/richonn/kubeforge-frontend
    tag: sha-2812875
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 50

worker:
  replicaCount: 1
  image:
    repository: ghcr.io/richonn/kubeforge-worker
    tag: sha-2812875
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 50
