api:
  replicaCount: 1
  image:
    repository: ghcr.io/richonn/kubeforge-api
    tag: sha-020cca8
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/richonn/kubeforge-frontend
    tag: sha-020cca8
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

worker:
  replicaCount: 1
  image:
    repository: ghcr.io/richonn/kubeforge-worker
    tag: sha-020cca8
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
