name: Build

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, frontend, worker]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: app/${{ matrix.service }}
          push: false
          load: true
          tags: ghcr.io/richonn/kubeforge-${{ matrix.service }}:ci

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/richonn/kubeforge-${{ matrix.service }}:ci
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
          ignore-unfixed: true
