name: CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
      - 'infra/**'
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  scan:
    if: github.event_name == 'push'
    needs: build
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  push:
    if: github.event_name == 'push'
    needs: scan
    uses: ./.github/workflows/push.yml
    secrets: inherit

  bump:
    if: github.event_name == 'push'
    needs: push
    uses: ./.github/workflows/bump.yml
    permissions:
      contents: write
