name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, frontend, worker]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: app/${{ matrix.service }}
          push: false
          tags: ghcr.io/richonn/kubeforge-${{ matrix.service }}:ci

  push:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, frontend, worker]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/richonn/kubeforge-${{ matrix.service }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=sha-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
